C Versus Fortran order

In [1]:
import numpy as np

In [2]:
arr = np.arange(12).reshape((3,4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2 = np.array([[7,8,9],[10,11,12]])

In [9]:
np.concatenate([arr1,arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
np.concatenate([arr1,arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [11]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

split , on the other hand, slices apart an array into multiple arrays along an axis:

In [13]:
arr = np.random.randn(5,2)

In [14]:
arr

array([[ 0.48728273,  0.11538057],
       [-0.66329897, -0.47242807],
       [-0.50109273,  0.21499914],
       [-0.5087375 ,  1.25651825],
       [-0.125278  , -0.33429147]])

In [15]:
first,second,third = np.split(arr,[1,3])

In [16]:
first

array([[0.48728273, 0.11538057]])

In [17]:
second

array([[-0.66329897, -0.47242807],
       [-0.50109273,  0.21499914]])

In [18]:
third

array([[-0.5087375 ,  1.25651825],
       [-0.125278  , -0.33429147]])

### Stacking helpers: r_ and c_

There are two special objects in the NumPy namespace, r_ and c_ , that make stacking
arrays more concise:

In [19]:
arr = np.arange(6)

In [20]:
arr1 = arr.reshape((3,2))

In [21]:
arr2 = np.random.randn(3,2)

In [22]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.58436688,  0.76819914],
       [ 0.07083389, -0.06681947],
       [ 0.72026148, -1.31704598]])

In [23]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-1.58436688,  0.76819914,  3.        ],
       [ 0.07083389, -0.06681947,  4.        ],
       [ 0.72026148, -1.31704598,  5.        ]])

In [24]:
## These additionally can translate slices to arrays:
np.c_[1:6,-10:-5]
## See the docstring for more on what you can do with c_ and r_ .

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: tile and repeat

In [25]:
arr =np.arange(3)

In [26]:
arr

array([0, 1, 2])

In [27]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [28]:
arr

array([0, 1, 2])

In [29]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

##### Multidimensional arrays can have their elements repeated along a particular axis.

In [30]:
arr = np.random.randn(2,2)

In [31]:
arr

array([[-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774]])

In [32]:
arr.repeat(2,axis=0)

array([[-0.20503128, -1.21033052],
       [-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774],
       [ 1.95985666, -0.46992774]])

In [33]:
arr.repeat([2,3],axis=0)

array([[-0.20503128, -1.21033052],
       [-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774],
       [ 1.95985666, -0.46992774],
       [ 1.95985666, -0.46992774]])

In [34]:
arr.repeat(2,axis=1)

array([[-0.20503128, -0.20503128, -1.21033052, -1.21033052],
       [ 1.95985666,  1.95985666, -0.46992774, -0.46992774]])

In [35]:
arr.repeat([2,3],axis=1)

array([[-0.20503128, -0.20503128, -1.21033052, -1.21033052, -1.21033052],
       [ 1.95985666,  1.95985666, -0.46992774, -0.46992774, -0.46992774]])

tile , on the other hand, is a shortcut for stacking copies of an array along an axis.
Visually you can think of it as being akin to “laying down tiles”:

In [36]:
arr

array([[-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774]])

In [37]:
np.tile(arr,2)

array([[-0.20503128, -1.21033052, -0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774,  1.95985666, -0.46992774]])

In [38]:
arr

array([[-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774]])

In [39]:
np.tile(arr,(2,1))

array([[-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774],
       [-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774]])

In [40]:
arr

array([[-0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774]])

In [41]:
np.tile(arr,(3,2))

array([[-0.20503128, -1.21033052, -0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774,  1.95985666, -0.46992774],
       [-0.20503128, -1.21033052, -0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774,  1.95985666, -0.46992774],
       [-0.20503128, -1.21033052, -0.20503128, -1.21033052],
       [ 1.95985666, -0.46992774,  1.95985666, -0.46992774]])

### Fancy Indexing Equivalents: take and put

In [42]:
arr= np.arange(10)*10

In [43]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
inds = [7,1,2,6]

In [45]:
arr[inds]

array([70, 10, 20, 60])

There are alternative ndarray methods that are useful in the special case of only making a selection on a single axis:

In [46]:
arr.take(inds)

array([70, 10, 20, 60])

In [47]:
arr.put(inds,42)

In [48]:
arr

array([ 0, 42, 42, 30, 40, 50, 42, 42, 80, 90])

In [49]:
arr

array([ 0, 42, 42, 30, 40, 50, 42, 42, 80, 90])

In [50]:
arr.put(inds,[40,41,42,43])

In [51]:
arr

array([ 0, 41, 42, 30, 40, 50, 43, 40, 80, 90])

To use take along other axes, you can pass the axis keyword:

In [52]:
inds = [2,0,2,1]

In [53]:
arr = np.random.randn(2,4)

In [54]:
arr

array([[ 0.59986612, -0.72842186,  0.71723792, -0.18654717],
       [ 1.68231116,  1.51233818, -0.11448902, -0.56836227]])

In [55]:
arr.take(inds,axis=1)

array([[ 0.71723792,  0.59986612,  0.71723792, -0.72842186],
       [-0.11448902,  1.68231116, -0.11448902,  1.51233818]])

put does not accept an axis argument but rather indexes into the flattened (one-
dimensional, C order) version of the array. Thus, when you need to set elements
using an index array on other axes, it is often easiest to use fancy indexing.

### Broadcasting

In [56]:
arr = np.random.randn(4, 3)

In [57]:
arr

array([[ 0.26281408, -1.06791316,  0.03318099],
       [ 0.50119717, -1.72020594,  0.44599077],
       [-0.13132056,  0.91943641,  0.88585108],
       [-0.27861593, -0.83531489,  0.41886329]])

In [58]:
arr.ndim

2

In [59]:
row_means = arr.mean(1)

In [60]:
row_means

array([-0.25730603, -0.25767267,  0.55798898, -0.23168918])

In [61]:
row_means.shape

(4,)

In [62]:
row_means.reshape(4,1)

array([[-0.25730603],
       [-0.25767267],
       [ 0.55798898],
       [-0.23168918]])

In [63]:
demeaned = arr - row_means.reshape((4,1))

In [64]:
demeaned.mean(1)

array([ 3.70074342e-17,  3.70074342e-17, -7.40148683e-17,  3.70074342e-17])

### Broadcasting Over Other Axes

In [65]:
arr

array([[ 0.26281408, -1.06791316,  0.03318099],
       [ 0.50119717, -1.72020594,  0.44599077],
       [-0.13132056,  0.91943641,  0.88585108],
       [-0.27861593, -0.83531489,  0.41886329]])

In [66]:
arr.mean(1)

array([-0.25730603, -0.25767267,  0.55798898, -0.23168918])

In [67]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [68]:
arr - arr.mean(0)

array([[ 1.74295395e-01, -3.91913763e-01, -4.12790545e-01],
       [ 4.12678480e-01, -1.04420655e+00,  1.92336443e-05],
       [-2.19839254e-01,  1.59543581e+00,  4.39879551e-01],
       [-3.67134621e-01, -1.59315498e-01, -2.71082400e-02]])

In [69]:
arr - arr.mean(1).reshape((4,1))

array([[ 0.52012011, -0.81060713,  0.29048702],
       [ 0.75886984, -1.46253327,  0.70366344],
       [-0.68930954,  0.36144743,  0.32786211],
       [-0.04692675, -0.60362572,  0.65055247]])

In [70]:
arr = np.zeros((4,4))

In [71]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
arr3d = arr[:,np.newaxis, :]

In [73]:
arr3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [74]:
arr3d.shape

(4, 1, 4)

In [75]:
arr_1d = np.random.normal(size=3)

In [76]:
arr_1d[:, np.newaxis]

array([[ 0.67748115],
       [-0.06969141],
       [-0.31157782]])

In [77]:
arr = np.random.randn(3,4,5)

In [78]:
depth_means = arr.mean(2)

In [79]:
depth_means

array([[-0.23012527,  0.18559027,  0.02738924, -0.11674219],
       [ 0.01516083,  0.13279691,  0.55779879, -0.51001683],
       [ 0.26863783,  0.25143869,  0.57376037,  0.88575019]])

In [80]:
depth_means.shape

(3, 4)

# Page 464 Missing

## Setting Array Values by Broadcasting

In [81]:
arr = np.zeros((4,3))

In [82]:
arr[:] = 5

In [83]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [84]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [85]:
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [86]:
arr[:] = col[:, np.newaxis]

In [87]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [88]:
arr[:2] = [[-1.37], [0.509]]

In [89]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

### Advanced ufunc Usage

In [90]:
arr = np.arange(10)

In [93]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.add.reduce(arr)

45

In [92]:
arr.sum()

45

In [94]:
np.random.seed(123456) # for reproducibility

In [95]:
arr = np.random.randn(5,5)

In [96]:
arr[::2].sort(1) # sort a few rows

In [97]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [99]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])