C Versus Fortran order

In [1]:
import numpy as np

In [2]:
arr = np.arange(12).reshape((3,4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr2 = np.array([[7,8,9],[10,11,12]])

In [10]:
np.concatenate([arr1,arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.concatenate([arr1,arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [13]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

split , on the other hand, slices apart an array into multiple arrays along an axis:

In [15]:
arr = np.random.randn(5,2)

In [16]:
arr

array([[-0.69492861, -0.64957535],
       [-0.06283978, -0.62152685],
       [-1.1806832 , -1.82027652],
       [ 1.56112617,  0.52008352],
       [-0.99427834,  0.65523126]])

In [17]:
first,second,third = np.split(arr,[1,3])

In [18]:
first

array([[-0.69492861, -0.64957535]])

In [19]:
second

array([[-0.06283978, -0.62152685],
       [-1.1806832 , -1.82027652]])

In [20]:
third

array([[ 1.56112617,  0.52008352],
       [-0.99427834,  0.65523126]])

### Stacking helpers: r_ and c_

There are two special objects in the NumPy namespace, r_ and c_ , that make stacking
arrays more concise:

In [21]:
arr = np.arange(6)

In [22]:
arr1 = arr.reshape((3,2))

In [23]:
arr2 = np.random.randn(3,2)

In [24]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.17208016,  0.07653227],
       [ 0.20654488, -0.0456851 ],
       [ 0.83514965,  0.06703255]])

In [25]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.17208016,  0.07653227,  3.        ],
       [ 0.20654488, -0.0456851 ,  4.        ],
       [ 0.83514965,  0.06703255,  5.        ]])

In [26]:
## These additionally can translate slices to arrays:
np.c_[1:6,-10:-5]
## See the docstring for more on what you can do with c_ and r_ .

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: tile and repeat

In [27]:
arr =np.arange(3)

In [28]:
arr

array([0, 1, 2])

In [29]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [30]:
arr

array([0, 1, 2])

In [31]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

##### Multidimensional arrays can have their elements repeated along a particular axis.

In [34]:
arr = np.random.randn(2,2)

In [35]:
arr

array([[-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738]])

In [36]:
arr.repeat(2,axis=0)

array([[-0.09902207, -1.24350109],
       [-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738],
       [ 1.56325869,  0.42026738]])

In [38]:
arr.repeat([2,3],axis=0)

array([[-0.09902207, -1.24350109],
       [-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738],
       [ 1.56325869,  0.42026738],
       [ 1.56325869,  0.42026738]])

In [37]:
arr.repeat(2,axis=1)

array([[-0.09902207, -0.09902207, -1.24350109, -1.24350109],
       [ 1.56325869,  1.56325869,  0.42026738,  0.42026738]])

In [39]:
arr.repeat([2,3],axis=1)

array([[-0.09902207, -0.09902207, -1.24350109, -1.24350109, -1.24350109],
       [ 1.56325869,  1.56325869,  0.42026738,  0.42026738,  0.42026738]])

tile , on the other hand, is a shortcut for stacking copies of an array along an axis.
Visually you can think of it as being akin to “laying down tiles”:

In [40]:
arr

array([[-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738]])

In [42]:
np.tile(arr,2)

array([[-0.09902207, -1.24350109, -0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738,  1.56325869,  0.42026738]])

In [43]:
arr

array([[-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738]])

In [45]:
np.tile(arr,(2,1))

array([[-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738],
       [-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738]])

In [46]:
arr

array([[-0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738]])

In [47]:
np.tile(arr,(3,2))

array([[-0.09902207, -1.24350109, -0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738,  1.56325869,  0.42026738],
       [-0.09902207, -1.24350109, -0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738,  1.56325869,  0.42026738],
       [-0.09902207, -1.24350109, -0.09902207, -1.24350109],
       [ 1.56325869,  0.42026738,  1.56325869,  0.42026738]])

### Fancy Indexing Equivalents: take and put

In [48]:
arr= np.arange(10)*10

In [49]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
inds = [7,1,2,6]

In [51]:
arr[inds]

array([70, 10, 20, 60])

There are alternative ndarray methods that are useful in the special case of only making a selection on a single axis:

In [52]:
arr.take(inds)

array([70, 10, 20, 60])

In [53]:
arr.put(inds,42)

In [54]:
arr

array([ 0, 42, 42, 30, 40, 50, 42, 42, 80, 90])

In [56]:
arr

array([ 0, 42, 42, 30, 40, 50, 42, 42, 80, 90])

In [57]:
arr.put(inds,[40,41,42,43])

In [58]:
arr

array([ 0, 41, 42, 30, 40, 50, 43, 40, 80, 90])

To use take along other axes, you can pass the axis keyword:

In [59]:
inds = [2,0,2,1]

In [60]:
arr = np.random.randn(2,4)

In [61]:
arr

array([[ 1.334594  ,  0.98486383,  0.41111455,  0.23125903],
       [ 0.98903685, -0.0779993 ,  0.63622726, -0.66024396]])

In [62]:
arr.take(inds,axis=1)

array([[ 0.41111455,  1.334594  ,  0.41111455,  0.98486383],
       [ 0.63622726,  0.98903685,  0.63622726, -0.0779993 ]])

put does not accept an axis argument but rather indexes into the flattened (one-
dimensional, C order) version of the array. Thus, when you need to set elements
using an index array on other axes, it is often easiest to use fancy indexing.

### Broadcasting

In [63]:
arr = np.random.randn(4, 3)

In [64]:
arr

array([[-0.4079417 , -1.80681881,  0.88265781],
       [-0.64242078,  0.14850756,  0.27346513],
       [-0.7545693 ,  0.70019965,  0.96867914],
       [ 0.9260441 ,  0.97285759, -0.6376953 ]])

In [65]:
arr.ndim

2

In [66]:
row_means = arr.mean(1)

In [67]:
row_means

array([-0.44403423, -0.0734827 ,  0.30476983,  0.42040213])

In [68]:
row_means.shape

(4,)

In [69]:
row_means.reshape(4,1)

array([[-0.44403423],
       [-0.0734827 ],
       [ 0.30476983],
       [ 0.42040213]])

In [72]:
demeaned = arr - row_means.reshape((4,1))

In [75]:
demeaned.mean(1)

array([ 0.00000000e+00, -1.85037171e-17,  0.00000000e+00,  0.00000000e+00])

### Broadcasting Over Other Axes

In [76]:
arr

array([[-0.4079417 , -1.80681881,  0.88265781],
       [-0.64242078,  0.14850756,  0.27346513],
       [-0.7545693 ,  0.70019965,  0.96867914],
       [ 0.9260441 ,  0.97285759, -0.6376953 ]])

In [77]:
arr.mean(1)

array([-0.44403423, -0.0734827 ,  0.30476983,  0.42040213])

In [78]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [79]:
arr - arr.mean(0)

array([[-0.18821978, -1.81050531,  0.51088112],
       [-0.42269886,  0.14482107, -0.09831157],
       [-0.53484738,  0.69651315,  0.59690244],
       [ 1.14576602,  0.96917109, -1.00947199]])

In [80]:
arr - arr.mean(1).reshape((4,1))

array([[ 0.03609254, -1.36278458,  1.32669204],
       [-0.56893808,  0.22199026,  0.34694782],
       [-1.05933913,  0.39542982,  0.66390931],
       [ 0.50564197,  0.55245546, -1.05809743]])

In [81]:
arr = np.zeros((4,4))

In [82]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
arr3d = arr[:,np.newaxis, :]

In [84]:
arr3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [85]:
arr3d.shape

(4, 1, 4)

In [86]:
arr_1d = np.random.normal(size=3)

In [88]:
arr_1d[:, np.newaxis]

array([[-0.65809614],
       [-0.72677726],
       [-0.52936627]])

In [89]:
arr = np.random.randn(3,4,5)

In [90]:
depth_means = arr.mean(2)

In [91]:
depth_means

array([[ 0.14508589, -0.02865129, -0.34855036, -0.1235605 ],
       [-1.25611591, -0.26209931,  0.08099319, -1.0754818 ],
       [-0.77464404,  0.75509768, -0.29646557,  0.64718414]])

In [92]:
depth_means.shape

(3, 4)

# Page 464 Missing

## Setting Array Values by Broadcasting

In [93]:
arr = np.zeros((4,3))

In [94]:
arr[:] = 5

In [95]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [100]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [101]:
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [102]:
arr[:] = col[:, np.newaxis]

In [103]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [105]:
arr[:2] = [[-1.37], [0.509]]

In [106]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

### Advanced ufunc Usage

In [107]:
arr = np.arange(10)

In [108]:
np.add.reduce(arr)

45

In [109]:
arr.sum()

45