### Starting from 3D Arrays

In [1]:
import numpy as np

In [2]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [3]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
# arr3d[0] is a 2 × 3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3d.ndim

3

In [6]:
arr3d.shape

(2, 2, 3)

Both scalar values and arrays can be assigned to arr3d[0] 

In [7]:
old_values = arr3d[0].copy()

In [9]:
arr3d[0] = 42

In [10]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3d[0] = old_values

In [13]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0) ,
forming a 1-dimensional array:

In [14]:
arr3d[1,0]

array([7, 8, 9])

In [16]:
#explaination
x = arr3d[1]

In [17]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
x[0]

array([7, 8, 9])

### Indexing with slices

In [19]:
arr = np.arange(10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [23]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [24]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can pass multiple slices just like you can pass multiple indexes:

In [29]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [33]:
arr2d[1,:2]

array([4, 5])

Similarly, I can select the third column but only the first two rows like so:

In [35]:
arr2d[:2,2]

array([3, 6])