### Starting from 3D Arrays

In [1]:
import numpy as np

In [2]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [3]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
# arr3d[0] is a 2 × 3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3d.ndim

3

In [6]:
arr3d.shape

(2, 2, 3)

Both scalar values and arrays can be assigned to arr3d[0] 

In [7]:
old_values = arr3d[0].copy()

In [8]:
arr3d[0] = 42

In [9]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr3d[0] = old_values

In [12]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0) ,
forming a 1-dimensional array:

In [13]:
arr3d[1,0]

array([7, 8, 9])

In [14]:
#explaination
x = arr3d[1]

In [15]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
x[0]

array([7, 8, 9])

### Indexing with slices

In [17]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [20]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can pass multiple slices just like you can pass multiple indexes:

In [23]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [24]:
arr2d[1,:2]

array([4, 5])

Similarly, I can select the third column but only the first two rows like so:

In [25]:
arr2d[:2,2]

array([3, 6])

In [26]:
x = arr2d[:2,1:]

In [27]:
x.shape

(2, 2)

In [28]:
x = arr2d[2]
x


array([7, 8, 9])

In [29]:
x.shape

(3,)

In [30]:
x = arr2d[2:,:]

In [31]:
x

array([[7, 8, 9]])

In [32]:
x.shape

(1, 3)

In [33]:
# 2nd-Day April/21/2020 

In [35]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x = arr2d[:2,1:]

In [39]:
x

array([[2, 3],
       [5, 6]])

In [37]:
x.ndim

2

In [38]:
x.shape

(2, 2)

In [40]:
x = arr2d[2]

In [41]:
x

array([7, 8, 9])

In [42]:
x.ndim

1

In [43]:
x.shape

(3,)

In [44]:
x = arr2d[2,:]

In [45]:
x

array([7, 8, 9])

In [46]:
x.ndim

1

In [47]:
x.shape

(3,)

In [48]:
x = arr2d[2:,:]

In [49]:
x

array([[7, 8, 9]])

In [51]:
x = arr2d[:,:2]

In [52]:
x

array([[1, 2],
       [4, 5],
       [7, 8]])

In [53]:
x.ndim

2

In [54]:
x.shape

(3, 2)

In [57]:
x = arr2d[1,:2]

In [58]:
x

array([4, 5])

In [59]:
x.ndim

1

In [60]:
x.shape

(2,)

In [61]:
x = arr2d[1:2, :2]

In [62]:
x.ndim

2

In [63]:
x.shape

(1, 2)

### Boolean Indexing

In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [65]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [66]:
data = np.random.randn(7,4)

In [67]:
data

array([[ 1.33787398,  0.98676649,  1.11988762,  0.08561694],
       [-0.48869829,  0.44708394,  1.60349635,  1.08553153],
       [ 0.61705839, -0.37182721,  1.92846682,  0.12969315],
       [ 1.42214664, -0.21348842, -0.75918564, -0.34443261],
       [ 0.30322252, -0.27014724,  0.72114091,  0.30436383],
       [-0.04375007, -0.0908595 , -0.91334794, -1.43884528],
       [-1.36703014,  0.13776737,  1.07007143, -1.21087901]])

In [68]:
data.ndim

2

In [69]:
data.shape

(7, 4)

In [70]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [71]:
data[names == 'Bob']

array([[ 1.33787398,  0.98676649,  1.11988762,  0.08561694],
       [ 1.42214664, -0.21348842, -0.75918564, -0.34443261]])

In [72]:
data[names == 'Bob',2:] 

array([[ 1.11988762,  0.08561694],
       [-0.75918564, -0.34443261]])

In [73]:
data[names == 'Bob',3] 

array([ 0.08561694, -0.34443261])

In [74]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [75]:
data[~(names == 'Bob')]

array([[-0.48869829,  0.44708394,  1.60349635,  1.08553153],
       [ 0.61705839, -0.37182721,  1.92846682,  0.12969315],
       [ 0.30322252, -0.27014724,  0.72114091,  0.30436383],
       [-0.04375007, -0.0908595 , -0.91334794, -1.43884528],
       [-1.36703014,  0.13776737,  1.07007143, -1.21087901]])

In [76]:
data

array([[ 1.33787398,  0.98676649,  1.11988762,  0.08561694],
       [-0.48869829,  0.44708394,  1.60349635,  1.08553153],
       [ 0.61705839, -0.37182721,  1.92846682,  0.12969315],
       [ 1.42214664, -0.21348842, -0.75918564, -0.34443261],
       [ 0.30322252, -0.27014724,  0.72114091,  0.30436383],
       [-0.04375007, -0.0908595 , -0.91334794, -1.43884528],
       [-1.36703014,  0.13776737,  1.07007143, -1.21087901]])

In [77]:
data[data < 0] =0

In [78]:
data

array([[1.33787398, 0.98676649, 1.11988762, 0.08561694],
       [0.        , 0.44708394, 1.60349635, 1.08553153],
       [0.61705839, 0.        , 1.92846682, 0.12969315],
       [1.42214664, 0.        , 0.        , 0.        ],
       [0.30322252, 0.        , 0.72114091, 0.30436383],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.13776737, 1.07007143, 0.        ]])

In [79]:
data[names != 'Joe'] =7

In [80]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.44708394, 1.60349635, 1.08553153],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.13776737, 1.07007143, 0.        ]])

As we will see later, these types of operations on two-dimensional data are convenient
to do with pandas.

### Fancy Indexing

In [90]:
arr = np.empty((8,4))

In [91]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [92]:
for i in range(8):
    arr[i] = i

In [93]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [86]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [87]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a one-
dimensional array of elements corresponding to each tuple of indices:

In [96]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [97]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

We’ll look at the reshape method in more detail in Appendix A.

the result of fancy indexing is always one-dimensional.

In [98]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [100]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [101]:
arr = np.arange(15).reshape((3,5))

In [102]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [113]:
arr = np.random.randn(6,3)

In [114]:
arr

array([[-9.45420514e-01,  7.05600540e-05,  1.59620611e-01],
       [-7.44049136e-02, -6.05984382e-01,  4.53695921e-01],
       [-8.19748937e-02,  1.10831583e+00,  3.22542012e+00],
       [-4.63687348e-01,  7.55371991e-02, -2.34423076e-01],
       [ 6.36755343e-01, -1.14240284e+00,  1.58600241e+00],
       [ 3.30341882e-01, -1.11946653e+00,  7.13197444e-02]])

In [115]:
np.dot(arr.T,arr)

array([[ 1.63566501, -1.178096  ,  0.69308515],
       [-1.178096  ,  4.15957646,  1.39046141],
       [ 0.69308515,  1.39046141, 13.21009803]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes (for extra mind bending):

In [130]:
arr = np.arange(16).reshape((2,2,4))

In [131]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [132]:
arr.ndim

3

In [124]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [125]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [126]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [129]:
arr.ndim

3

In [133]:
arr.shape

(2, 2, 4)

### Universal Functions: Fast Element-Wise Array Functions

In [134]:
arr = np.arange(10)

In [135]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [138]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [139]:
## These were unary ufunctions. Others such as take
## two arrays (binary functions) and return a 
## single array as the result

In [140]:
x = np.random.randn(8)

In [141]:
y = np.random.randn(8)

In [142]:
x

array([-0.87176254, -0.34455844,  0.35890745, -1.13369513, -0.95997602,
        0.4422124 , -0.35821679, -1.22005926])

In [143]:
y

array([-0.93804507, -0.43642327,  2.69287608, -0.15323654, -1.60393265,
        0.18055167, -0.22322174, -1.07660754])

In [144]:
np.maximum(x,y)

array([-0.87176254, -0.34455844,  2.69287608, -0.15323654, -0.95997602,
        0.4422124 , -0.22322174, -1.07660754])

In [145]:
arr = np.random.randn(7)*5

In [146]:
arr

array([-0.10154897,  7.8500922 , -6.4378917 ,  5.28087637, -7.78134718,
        5.00980489,  0.40868152])

In [148]:
remainder, whole_part = np.modf(arr)

In [149]:
remainder

array([-0.10154897,  0.8500922 , -0.4378917 ,  0.28087637, -0.78134718,
        0.00980489,  0.40868152])

In [150]:
whole_part

array([-0.,  7., -6.,  5., -7.,  5.,  0.])

In [151]:
arr

array([-0.10154897,  7.8500922 , -6.4378917 ,  5.28087637, -7.78134718,
        5.00980489,  0.40868152])

In [153]:
np.sqrt(arr)

/home/talha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.8018016 ,        nan, 2.29801575,        nan,
       2.23825934, 0.63928203])

In [154]:
np.sqrt(arr,arr)

/home/talha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.8018016 ,        nan, 2.29801575,        nan,
       2.23825934, 0.63928203])

## Array-Oriented Programming with Arrays

Later, in Appendix A, It'll explain broadcasting, a powerful method for vectorizing computations.

In [155]:
points = np.arange(-5,5,0.01) # 1000 equally spaced points

In [156]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [157]:
xs, ys = np.meshgrid(points,points)

In [158]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])