## Numpy Vs Python

In [1]:
import numpy as np

In [2]:
l = range(1000000)

In [4]:
d = np.arange(1000000)

In [5]:
%time for i in range(1,10): r=[x*2 for x in l]

CPU times: user 528 ms, sys: 88.9 ms, total: 617 ms
Wall time: 616 ms


In [6]:
%time for i in range(1,10): r=d*2

CPU times: user 25.6 ms, sys: 73 µs, total: 25.7 ms
Wall time: 24.2 ms


## Multidimensional Array

In [7]:
np.zeros((4,4))
# create an array with values 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((7,7))

array([[6.93465841e-310, 4.67198712e-310, 1.67500032e+243,
        1.76413078e+156, 1.79805224e+044, 3.47725093e+185,
        8.78411349e+247],
       [7.21901493e+159, 1.17567364e+214, 1.27826910e-152,
        2.08804617e-115, 6.46572285e+170, 1.10633865e+200,
        1.05604052e+267],
       [4.51634594e+217, 1.05019735e-153, 5.82471374e+257,
        1.69593624e-152, 9.35319239e+252, 5.75680933e+252,
        2.37269831e+267],
       [6.01346953e-154, 4.70107982e+180, 7.20185273e+159,
        8.82893671e+199, 6.01346953e-154, 1.33360291e+241,
        1.53584743e-253],
       [2.64089007e-313, 2.98233776e-308, 1.33360296e+241,
        8.39037136e-311, 3.22635710e-307, 2.03016870e-316,
        4.16865225e+199],
       [1.43762582e+217, 4.61249234e-303, 3.10362194e+175,
        1.05335199e+277, 3.81291163e+180, 1.71387267e+214,
        4.79129674e-309],
       [5.80220124e+180, 2.12369026e+127, 4.24297177e+228,
        7.80002581e-271, 8.36775750e+242, 2.95806213e-311,
        5.03961303

In [11]:
l = [1,4,5,7]

In [12]:
np.array(l)

array([1, 4, 5, 7])

In [14]:
x = np.arange(1,100,10)

In [16]:
x.shape

(10,)

In [17]:
z = np.zeros((10,10))

In [18]:
z.shape

(10, 10)

In [20]:
r = z.reshape((2,2,5,5))

In [21]:
r

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [22]:
r.dtype

dtype('float64')

In [23]:
r.ndim

4

## Arithmetic with ndarray

In [24]:
## Operations on two metrics

In [25]:
arr = np.array([[1,2,3],[4,5,6]])

In [26]:
arr.shape

(2, 3)

In [27]:
arr.ndim

2

In [28]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
## Operation with scalar

In [30]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
2*arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
## comparison between metrics

In [35]:
arr2 = np.array([[1,2,3],[4,5,6]]) 

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr < arr2

array([[False, False, False],
       [False, False, False]])

####  Vectorized Operations

In [41]:
a = np.random.randn((10))

In [42]:
b = np.random.randn((10))

In [43]:
a

array([-0.37647303,  1.15492758, -0.85758882,  0.18620013, -0.42300066,
        0.09155846,  0.86151991, -0.84962845, -1.37421038, -0.15970705])

In [44]:
b

array([-0.68263584, -0.14071932, -0.98198156,  0.80452976,  1.28557315,
        0.63876303,  0.84027369,  0.38073078, -0.82923981,  2.02820494])

In [45]:
a+b

array([-1.05910886,  1.01420826, -1.83957038,  0.99072989,  0.86257249,
        0.73032149,  1.70179359, -0.46889767, -2.20345019,  1.86849789])

In [46]:
a-b

array([ 0.30616281,  1.2956469 ,  0.12439274, -0.61832962, -1.7085738 ,
       -0.54720457,  0.02124622, -1.23035922, -0.54497057, -2.18791199])

In [47]:
a*2

array([-0.75294605,  2.30985516, -1.71517764,  0.37240026, -0.84600131,
        0.18311692,  1.72303981, -1.6992569 , -2.74842076, -0.3194141 ])

In [48]:
1/a

array([-2.6562328 ,  0.86585515, -1.16605998,  5.37056549, -2.36406252,
       10.92198383,  1.16073929, -1.17698507, -0.72769062, -6.26146438])

In [49]:
a>0

array([False,  True, False,  True, False,  True,  True, False, False,
       False])

In [50]:
a[a>0]

array([1.15492758, 0.18620013, 0.09155846, 0.86151991])

## Indexing & Slicing

In [51]:
x = np.array([1,7,9,8,5])

In [52]:
x[4]

5

In [53]:
x[x>5]

array([7, 9, 8])

In [55]:
x[[2,1]]   #fancy indexing

array([9, 7])

In [56]:
x = np.random.randn(10,10)

In [57]:
x

array([[-0.11257827, -1.52231294,  1.82977998,  0.9425226 ,  1.0333815 ,
        -1.39571341, -0.57071103, -1.87939741,  1.25797449, -0.78441185],
       [-0.74979179,  0.53628052, -0.7566688 , -1.19260515,  0.22285796,
        -1.10784488, -0.66418074, -0.32057549, -0.86667636, -0.09107275],
       [ 0.20895407,  2.15807821, -0.34743186, -2.12387692,  0.25640648,
        -0.81083186, -1.66439325, -0.32625084,  0.23327063,  0.238674  ],
       [ 1.53399923,  0.09893394, -1.32580131, -1.1452029 , -1.62124276,
        -0.77121203, -0.3693078 , -1.63365146, -0.52428079,  0.36787267],
       [-0.85584011, -0.01829671,  0.49028278,  1.81710455,  0.85333309,
        -1.23302151,  1.13655095, -1.26859232,  1.42454056,  0.03960068],
       [-0.62718915, -1.01377106,  1.48119292,  0.26213509, -0.50338409,
        -0.17060777,  0.32924096, -1.34386089,  0.08027852, -0.25616623],
       [ 0.38319433,  0.41551068, -0.69808816,  0.23526227,  0.16165379,
         0.76438757, -0.62873329,  1.16955905

In [59]:
x.ndim

2

In [60]:
x.shape

(10, 10)

In [61]:
x[0]

array([-0.11257827, -1.52231294,  1.82977998,  0.9425226 ,  1.0333815 ,
       -1.39571341, -0.57071103, -1.87939741,  1.25797449, -0.78441185])

In [62]:
x[0][4]

1.0333815029623172

In [63]:
x[1:10:2]

array([[-0.74979179,  0.53628052, -0.7566688 , -1.19260515,  0.22285796,
        -1.10784488, -0.66418074, -0.32057549, -0.86667636, -0.09107275],
       [ 1.53399923,  0.09893394, -1.32580131, -1.1452029 , -1.62124276,
        -0.77121203, -0.3693078 , -1.63365146, -0.52428079,  0.36787267],
       [-0.62718915, -1.01377106,  1.48119292,  0.26213509, -0.50338409,
        -0.17060777,  0.32924096, -1.34386089,  0.08027852, -0.25616623],
       [ 0.34827489, -0.19099988,  0.18206047,  3.01882547, -0.92535619,
         0.85954018, -0.3123366 ,  0.27934367,  0.10066675,  0.26408616],
       [ 0.60447141, -1.35733174, -0.36326563, -0.73036268,  1.39719783,
         1.96311849,  0.12295519, -0.64878488,  0.21885971, -0.62082009]])

In [64]:
x[::,0:4]

array([[-0.11257827, -1.52231294,  1.82977998,  0.9425226 ],
       [-0.74979179,  0.53628052, -0.7566688 , -1.19260515],
       [ 0.20895407,  2.15807821, -0.34743186, -2.12387692],
       [ 1.53399923,  0.09893394, -1.32580131, -1.1452029 ],
       [-0.85584011, -0.01829671,  0.49028278,  1.81710455],
       [-0.62718915, -1.01377106,  1.48119292,  0.26213509],
       [ 0.38319433,  0.41551068, -0.69808816,  0.23526227],
       [ 0.34827489, -0.19099988,  0.18206047,  3.01882547],
       [ 0.06359474,  0.60649943, -0.8563349 ,  0.46144451],
       [ 0.60447141, -1.35733174, -0.36326563, -0.73036268]])

In [65]:
x[1:-1,1:-1]=0

In [66]:
x

array([[-0.11257827, -1.52231294,  1.82977998,  0.9425226 ,  1.0333815 ,
        -1.39571341, -0.57071103, -1.87939741,  1.25797449, -0.78441185],
       [-0.74979179,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.09107275],
       [ 0.20895407,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.238674  ],
       [ 1.53399923,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.36787267],
       [-0.85584011,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.03960068],
       [-0.62718915,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.25616623],
       [ 0.38319433,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        

In [ ]:
#################################################################################################
#################################################################################################
#################################################################################################
#################################################################################################
#################################################################################################
                                    checkerboard Chessboard
#################################################################################################
#################################################################################################
#################################################################################################
#################################################################################################


## Fast Element wise array functions

In [67]:
x= np.array([10,9,8,6,11])

In [68]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [69]:
np.power(x,2)

array([100,  81,  64,  36, 121])

In [72]:
y = [7,1,33,3,-1]
np.maximum(x,y)

array([10,  9, 33,  6, 11])

## Np.where

In [73]:
salary = np.array([0,-1,100000,500000])                                  

In [75]:
np.where(salary <=0, 25000,salary)

array([ 25000,  25000, 100000, 500000])

In [76]:
np.where(salary<=0, "Not okay","OK")

array(['Not okay', 'Not okay', 'OK', 'OK'], dtype='<U8')

## Mathematical & Statistical Methods

In [79]:
## mean() cumsum() cumprod()
## boolean arrays 
## sum() any() all()
## np.sort()
## np.unique()

In [80]:
x = np.array([10,9,7,10,7])

In [81]:
x.mean()

8.6

In [82]:
x.cumsum()

array([10, 19, 26, 36, 43])

In [83]:
x.cumprod()

array([   10,    90,   630,  6300, 44100])

In [85]:
y = x>6

In [86]:
y

array([ True,  True,  True,  True,  True])

In [87]:
y.sum()

5

In [91]:
y.any()

True

In [92]:
y.all()

True

In [93]:
y = x > 7

In [94]:
y

array([ True,  True, False,  True, False])

In [95]:
y.sum()

3

In [97]:
x

array([10,  9,  7, 10,  7])

In [98]:
x.sort()

In [99]:
x

array([ 7,  7,  9, 10, 10])

In [100]:
np.unique(x)

array([ 7,  9, 10])

## File Input Output

In [ ]:
## np.save()
## np.load()
## np.savez

In [101]:
x = [1,4,5,7]

In [102]:
y = [8,6,9]

In [103]:
np.save('testx',x)

In [104]:
loadx = np.load('testx.npy')

In [105]:
loadx

array([1, 4, 5, 7])

In [110]:
np.savez('testxy',x=x,y=y)

In [111]:
loadxy = np.load('testxy.npz')

In [112]:
loadxy

In [113]:
loadxy['x']

array([1, 4, 5, 7])

In [115]:
loadxy['y']

array([8, 6, 9])

## Linear Algebra Functions

In [118]:
x = np.random.randn(3,2)

In [119]:
y = np.random.randn(2,3)

In [120]:
x.dot(y)

array([[-0.00808137, -0.44493969, -0.3272565 ],
       [-1.0848789 , -1.15963006, -1.53988673],
       [ 0.58830601,  1.20804643,  1.25426266]])

In [121]:
x.transpose()

array([[-0.24453192,  0.78462581, -0.09310213],
       [-0.62036862, -0.36208706,  1.01633085]])

## Pseudo Random Number

In [ ]:
## pseudo-random number generation
## normal()
## seed()
## gamma()
## uniform()

In [122]:
np.random.seed(7)

In [123]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [124]:
np.random.uniform(size = (4,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992]])

# Advanced Numpy Manipulation
## Reshape

In [125]:
x = np.random.randn(4,5)

In [126]:
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [127]:
x.reshape((2,2,5))

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [128]:
x.reshape((2,2,5) , order='F')

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936]],

       [[-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [129]:
x.reshape((2,2,-1))

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [130]:
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [131]:
x.ravel()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

In [132]:
x.flatten()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

## Concatenate

In [134]:
x = [[1,3,5],[7,9,0]]

In [135]:
arr1 = np.array(x)

In [136]:
y = [[11,13,15],[17,19,10]]

In [137]:
arr2=np.array(y)

In [138]:
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [139]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [140]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [141]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

## Split

In [142]:
x = [1,4,5,6,7,9,1,4]

In [143]:
d = np.array(x)

In [145]:
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [146]:
x = [[1,4,5,6,7,9,1,4] , [11,14,15,16,17,19,11,14]]

In [147]:
d = np.array(x)

In [148]:
np.split(d,[4,6], axis=1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  9],
        [17, 19]]), array([[ 1,  4],
        [11, 14]])]

## Tile & Repeat

In [150]:
d = np.array([1,5,7,8])

In [151]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [152]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])